language: r
r: 3.5.1
dist: xenial
cache:
    - packages
    - directories:
        - $TRAVIS_BUILD_DIR/ve-lib

# We don't need much of the history
git:
  depth: 1
  
# Be less strict when checking our package
warnings_are_errors: false

# Need some additional libraries under ubuntu
addons:
  apt:
    packages:
    - libudunits2-dev
    - libgdal-dev

# Set up the pair of cache areas
install:
  - mkdir -p $TRAVIS_BUILD_DIR/ve-lib
  - Rscript build/install-deps.R

# https://docs.travis-ci.com/user/build-stages#warming-up-a-cache-with-expensive-dependencies

# Dependence Information from original .travis.yml

#    - Folder=Sources/Framework/Visioneval            Depends=
#    - Folder=Sources/Modules/Ve2001Nhts              Depends=
#    - Folder=Sources/Modules/Vehouseholdtravel       Depends=Ve2001Nhts
#    - Folder=Sources/Modules/Vehouseholdvehicles     Depends=Ve2001Nhts,Vehouseholdtravel
#    - Folder=Sources/Modules/Velanduse               Depends=Ve2001Nhts,Vesimhouseholds
#    - Folder=Sources/Modules/Vesimhouseholds         Depends=
#    - Folder=Sources/Modules/Vesyntheticfirms        Depends=
#    - Folder=Sources/Modules/Vetransportsupply       Depends=
#    - Folder=Sources/Modules/Vetransportsupplyuse    Depends=
#    - Folder=Sources/Modules/Vetravelperformance     Depends=Ve2001Nhts,Vehouseholdtravel,Vepowertrainsandfuels
#    - Folder=Sources/Modules/Vepowertrainsandfuels   Depends=Ve2001Nhts,Vehouseholdtravel
#    - Folder=Sources/Modules/Vereports               Depends=Ve2001Nhts,Vehouseholdtravel
#    # - Folder=Sources/Modules/Vescenario            Depends=
#    - Folder=Sources/Models/Baseyearverpat           Depends=Ve2001Nhts,Vesimhouseholds,Vesyntheticfirms,Velanduse,Vetransportsupply,Vehouseholdtravel,Vehouseholdvehicles,Vetransportsupplyuse,Vereports
#    - Folder=Sources/Models/Verpat                   Depends=Ve2001Nhts,Vesimhouseholds,Vesyntheticfirms,Velanduse,Vetransportsupply,Vehouseholdtravel,Vehouseholdvehicles,Vetransportsupplyuse,Vereports
#    - Folder=Sources/Models/Verspm/Test1             Depends=Ve2001Nhts,Vesimhouseholds,Velanduse,Vetransportsupply,Vehouseholdtravel,Vehouseholdvehicles,Vepowertrainsandfuels,Vetravelperformance
#    - Folder=Sources/Vegui                           Depends=Ve2001Nhts,Vesimhouseholds,Vesyntheticfirms,Velanduse,Vetransportsupply,Vehouseholdtravel,Vehouseholdvehicles,Vetransportsupplyuse,Vereports

# Master library location for built VE modules so they don't confuse the package cache
env:
    global: VE_LIBRARY=$TRAVIS_BUILD_DIR/ve-lib

# Set up job stage processing to incrementally build and test VE
# packages.  No individual job runs for over 30 minutes, total run time
# 1:40 to 2:10 (the latter if R package cached needs to be built).

jobs:
    include:
        - stage: Build cache
          script: true
        - stage: VisionEval
          script: bash build/make-module.sh sources/framework/visioneval
        - stage: Group 1 Modules
          script:
            - bash build/make-module.sh sources/modules/VE2001NHTS
            - bash build/make-module.sh sources/modules/VEScenario
            - bash build/make-module.sh sources/modules/VESimHouseholds
            - bash build/make-module.sh sources/modules/VESyntheticFirms
            - bash build/make-module.sh sources/modules/VETransportSupply
            - bash build/make-module.sh sources/modules/VETransportSupplyUse
        - stage: Group 2 Modules
          script:
            - bash build/make-module.sh sources/modules/VEHouseholdTravel
            - bash build/make-module.sh sources/modules/VELandUse
            - bash build/make-module.sh sources/modules/VEPowertrainsAndFuels
        - stage: Group 3 Modules
          script:
            - bash build/make-module.sh sources/modules/VEHouseholdVehicles
            - bash build/make-module.sh sources/modules/VETravelPerformance
            - bash build/make-module.sh sources/modules/VEReports
        - stage: Group 4 Modules
          script:
            - bash build/make-module.sh sources/modules/VETravelPerformance
        - stage: Models and VEGUI (parallel)
          script: bash build/run-model.sh sources/models/BaseYearVERPAT/run_model.R
        - script: bash build/run-model.sh sources/models/VERPAT/run_model.R
        - script: bash build/run-model.sh sources/models/VERSPM/Test1/run_model.R
        - script: bash build/run-model.sh sources/VEGUI/run_vegui_test.R
        - stage: Cleanup
          script: rm -rf $VE_LIBRARY/*
